import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  header,
  children,
  footer

}: Readonly<{
  header: React.ReactNode
  children: React.ReactNode;
  footer: React.ReactNode
}>) {
  return (
    <html lang="en">
    <body>
      { header }
      <main>{children}</main>
      { footer }
    </body>
  </html>
  );
}
